[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "pyfastkron"
version = "1.0"
requires-python = ">=3.10"
build-frontend = {name = "build", args = ["--exports", "whole_archive"]}

[tool.scikit-build]
cmake.verbose = "true"

[tool.scikit-build.cmake.define]
PYMODULE="ON"
ENABLE_X86="ON"
ENABLE_CUDA="ON"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests/python",
]