[build-system]
requires = ["setuptools", "prebuilt_binaries"]
build-backend = "setuptools.build_meta"

[project]
name="pyfastkron"
authors=[{name="Abhinav Jangda", email="abhijangda@gmail.com"}]
requires-python= ">= 3.10"
version = "1.0"
#license
dependencies = [
    "numpy",
    "torch",
    "torchvision"
]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests/python",
]