[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "pyfastkron"
version = "0.0.1"
requires-python = ">=3.10"
build-frontend = {name = "build", args = ["--exports", "whole_archive"]}

[tool.scikit-build.cmake.define]
PYMODULE="ON"